### ISSUE TITLE
Errot when trying the demo.

### ISSUE THREAD

**Issue by TheBricktop** [freehuntx/godot-matcha#5]
"
Error
The following features required to run Godot projects on the Web are missing:
Cross Origin Isolation - Check web server configuration (send correct headers)
SharedArrayBuffer - Check web server configuration (send correct headers)
"

seems like the same errors that pop up when you try to upload a html game to the itch io page.

**Comment by jrburga** [comment]
This is a known issue with Godot 4.X HTML exports on itch. The fix is this: go into the itch.io where you uploaded your game, scroll down to the *Embed Options* settings. You should see an option for the following

> SharedArrayBuffer support — (Experimental) This may break parts of the page or your project. Only enable if you know you need it. [Learn more](https://itch.io/t/2025776/experimental-sharedarraybuffer-support)

Make sure that's *Enabled*.

Once it's enabled, reload the game and see if that works.

Otherwise, I'm not sure what else there is to do.

**Comment by freehuntx** [comment]
Did u try it in private mode? Private mode doesnt work with the coi workaround im using in github pages. Just try it locally. I cant fix this sadly in github pages since it doesnt add the headers.

**Comment by freehuntx** [comment]
Please make sure to allow serviceworkers. (Firefox private mode usually blocks this)
Then the "workaround" to fix the missing headers on github pages usually works.
