### ISSUE TITLE
Rooms with mesh connections

### ISSUE THREAD

**Issue by flametime** [freehuntx/godot-matcha#7]
Hi bro! 

You did a great job and made a very cool stuff!

Could you please make an example with rooms AND a mesh connection? So that multiple players can connect to one room 
(I tested the rooms and I couldn’t get them to work with more than 1 connection)

It would be amazing!

Thanks for the work you've done!

![gif_test](https://github.com/freehuntx/godot-matcha/assets/65140665/c3441d8e-55a3-40bd-93eb-1bd809acea72)

**Comment by freehuntx** [comment]
The bobble example is using mesh. If you mean the lobby system, thats still under development.
Im still struggling a bit with the mesh type because:
- Syncing peers is a bit tricky because you must make sure everybody uses the same node names
- Authoritive mesh mode would be nice (negotiating a host) but thats a bit tricky

But you can be sure i will keep improving the library :)

ps: U using i3? :sunglasses:
